export const UI = {
  swipeLike:        '¡Bacán! ❤️',
  swipePass:        'Ni ahí 👋',
  superLike:        '¡Entero filo! ⭐',
  esMatch:          '¡Se armó el cahuín! 🎉',
  esMatchSubtitulo: 'Los dos se eligieron po\' — ¡háblense al tiro!',
  sinMatches:       'Aún no tienes matches. ¡Sigue descubriendo po\'!',
  likesAgotados:    '¡Se acabaron tus likes por hoy! 😅',
  limiteGratis:     'Solo 5 likes por día en la versión gratis.',
  pasarePremium:    'Me subo a Cahuin Piola',
  premiumTitulo:    'Planes Cahuin',
  registroTitulo:   '¡Bienvenido a Cahuín! 🇨🇱',
  registroSub:      'Citas chilenas de verdad',
  siguente:         'Siguiente po\'',
  finalizar:        '¡Listo, a cahuinear! 🎉',
  errCampos:        'Rellena todos los campos po\'',
  errRUT:           'Ese RUT no es válido po\'',
  cuecaTitulo:      '🎵 La Cueca Digital',
  esMatch_cueca:    '¡La cueca terminó y se hizo match! 💃🕺',
  panoramasTitulo:  'Panoramas 🗺️',
  unirse:           '¡Me uno po\'! 🙌',
  cargando:         'Cargando...',
  guardar:          'Guardar cambios',
  cancelar:         'Cancelar',
};
